index:
    path: /
    controller: App\Controller\HomeController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

controllers:
    resource: ../src/Controller/
    type: attribute

api_controllers:
    resource: ../src/Controller/Api/
    type: attribute
    prefix: /api

search_results:
    path: /search
    controller: App\Controller\SearchController::search
