index:
    path: /
    controller: App\Controller\HomeController::index
login:
    path: /login
    controller: App\Controller\SecurityController::login

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
